# Generated by Django 4.1.5 on 2023-01-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_alter_endpoint_fail_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='fail_times',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
